name: "GitHub Action Demo triggered by"
on: workflow_dispatch
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Using step
        run: |
          for i in {1..10}
          do
            echo "This is iteration number 5 X $i = %i*5"
          done  
